include $(TOPDIR)/rules.mk

PKG_VERSION:=20250610
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for Frps
LUCI_DEPENDS:=+libc
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-frps

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
